# Generated by Django 5.1.6 on 2025-03-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_remove_customuser_groups_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
